GET http://localhost:3001/api/blogs/
###
GET http://localhost:3001/api/blogs/6a1d93dcf4e4ff383c4cfe49
###
POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
  "title": "yeralti",
  "author": "ali&sultan",
  "url": "www.mohammmed.com",
  "likes": 2,
  "id": "6a1c755963c6d82a29cf9e9b"
}

###
PUT http://localhost:3001/api/blogs/6a1d9401f4e4ff383c4cfe4a
Content-Type: application/json

{
    "title": "kuzy&guney",
    "author": "kuzey&cemre",
    "url": "www.mohammmed.com",
    "likes": 2,
    "id": "6a1d8a4658f4ea98e6ab5b16"
  }

###
DELETE http://localhost:3001/api/blogs/6a1d8a4658f4ea98e6ab5b16